yaml
name: Binder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r binder/requirements.txt

      - name: Build and deploy
        uses: jupyterhub/repo2docker-action@v2
        with:
          image: "xeus-env"
          user-id: 1000
          user-name: jovyan
          extra-build-args: |
            --build-arg NB_USER=jovyan
            --build-arg NB_UID=1000
            --build-arg NB_GID=100
